SHOW DATABASES;
USE BUSMANAGEMENTSYSTEM;
DROP TABLE BOOKING;
	CREATE TABLE booking(
		id INT PRIMARY KEY auto_increment,
		busNumber INT NOT NULL ,
		name VARCHAR(50) NOT NULL,
		date DATE ,
        bookingNumber VARCHAR(50)
	);